@startuml
'https://plantuml.com/deployment-diagram
title Deployment

folder "Bank on-premise" {
    node "Prod VMs" {
            [REST prod]
            [Bank data syncer prod]
            [Scheduler prod]
            [SMS Processor prod]
            [Push Processor prod]
            [Obfuscator]
            database "db prod"
    }
    node "Stage VMs" {
                [REST stage]
                [Bank data syncer stage]
                [Scheduler stage]
                [SMS Processor stage]
                [Push Processor stage]
                database "stage db"
        }
        node "Core" {
                        [Core prod]
                   [Core sandbox]
             queue "Kafka prod"
             queue "Kafka core sandbox"
        }
}

cloud "Digital cloud" {
    node "Dev VMs" {
        [REST]
        [Bank data syncer]
        [Scheduler]
        [SMS Processor]
        [Push Processor]
        queue Kafka
        database db
    }
}

@enduml